#ifndef TERRAIN_ASSETS_H
#define TERRAIN_ASSETS_H

#include "terrain_foundation.h"

enum ShaderAssets
{
    ASSET_SHADER_TEXTURE_VERTEX,
    ASSET_SHADER_TEXTURE_FRAGMENT,
    ASSET_SHADER_TERRAIN_VERTEX,
    ASSET_SHADER_TERRAIN_TESS_CTRL,
    ASSET_SHADER_TERRAIN_TESS_EVAL,
    ASSET_SHADER_TERRAIN_FRAGMENT,
    ASSET_SHADER_TERRAIN_COMPUTE_TESS_LEVEL,
    ASSET_SHADER_WIREFRAME_VERTEX,
    ASSET_SHADER_WIREFRAME_TESS_CTRL,
    ASSET_SHADER_WIREFRAME_TESS_EVAL,
    ASSET_SHADER_WIREFRAME_FRAGMENT,
    ASSET_SHADER_BRUSH_VERTEX,
    ASSET_SHADER_BRUSH_FRAGMENT,
    ASSET_SHADER_UI_VERTEX,
    ASSET_SHADER_UI_FRAGMENT,

    ASSET_SHADER_COUNT
};

EXPORT struct ShaderAsset
{
    uint32 handle;
};

EXPORT ShaderAsset *assetsGetShader(MemoryBlock *memory, uint32 assetId);

#endif